laravel/scout

- src/Engines/AlgoliaEngine.php
- src/Engines/Engine.php
- src/Engines/NullEngine.php
Make sure the docblocks and source code are consistent in the variable names. Previously, the docblocks would reflect `$query` and the code would actually be `$builder` or the other way around. Now, we're being consistent across the entire file and name any variable with an instance of the Builder `$builder`.
> Consistent naming across engines

- .travis.yml
as hhvm is no longer supported on 5.3
> hhvm doesn't need to be tested

- src/SearchableScope.php
Fixes #17 
`Builder` class is ambiguous in SearchableScope.php and it throws `FatalErrorException` when performing search.
> Fix Builder namespace

- src/SearchableScope.php
Fixes a bug that causes this error
```
[Symfony\Component\Debug\Exception\FatalThrowableError]                                                   
Type error: Argument 1 passed to Laravel\Scout\SearchableScope::Laravel\Scout\{closure}() must be an ins  
tance of Laravel\Scout\Builder, instance of Illuminate\Database\Eloquent\Builder given
```
Since an \Illuminate\Database\Eloquent\Builder doesn't extend Laravel\Scout\Builder to me the previous code will not work, these simple class name updates should fix the problem.
> Fix class names

- src/Engines/AlgoliaEngine.php
Right now, if query scopes mean a model is not visible to whatever maps results to models, then you'll get an undefined index error.
> Allow multi-tenancy with Algolia

- composer.json
- config/scout.php
- src/EngineManager.php
- src/Engines/ElasticsearchEngine.php
- src/SearchableScope.php
- tests/ElasticsearchEngineTest.php
- tests/Fixtures/AlgoliaEngineTestModel.php
- tests/Fixtures/ElasticsearchEngineTestModel.php
- tests/Fixtures/TestModel.php
Reopened since squashing would include other poeples commits from the upstream sync.
Initial Elasticsearch support, tests on the way.
Some options may differ and I may make a custom config key for customizing the query parameter, Elastic can be really complex but this setup should cover most scenarios.
Working right now:
- Searching
- Searching with where conditions
- Pagination
- Unit Testing :)
TODO:
- For future implementations, for both algolia and elastic, may the performSearch be a replaceable callback,so people can extend and customize it, gonna send a separate PR on it
> Initial Elasticsearch support

- .travis.yml
- src/Engines/ElasticsearchEngine.php
- tests/ElasticsearchEngineTest.php
There were errors in api calls for all elastiscsearch versions. This PR fixes it.  
It also adds actual tests against elasticsearch API and uses bulk api for inserts/deletes.
Perhaps even more tests would be required, as I already stumbled across various bugs
Travis Elasticsearch version is `1.4`. On my computer I was testing it using docker with Elasticsearch version `1.5` and `2.3.4`.
> Use bulk API for elasticsearch inserts and actually test elasticsearch.

- src/Builder.php
- src/Engines/AlgoliaEngine.php
- src/Engines/ElasticsearchEngine.php
- src/Engines/Engine.php
- src/Engines/NullEngine.php
- tests/BuilderTest.php
As mentioned in the Issue #46
```
->hasMorePagesWhen(($results->count() / $perPage) > $page)
```
always returns false because it is the result count will always match the `$perPage` parameter. To solve this issue i added a method to the engines called `getTotalCount()` that is used to get the correct count of the search results. The new builder code then looks like this:
```
->hasMorePagesWhen(($engine->getTotalCount($rawResults) / $perPage) > $page);
```
> Added getTotalCount() method to engines to solve pagination issues.

- src/Engines/ElasticsearchEngine.php
- tests/ElasticsearchEngineTest.php
Right now, if you query for, say, `category:foo`, you're gonna see an instance of `Elasticsearch\Common\Exceptions\BadRequest400Exception` thrown because `*category:foo*` is a syntax error in elasticsearch query strings.
All-in-all, `simple_query_string` (which cannot error and silently ignores bad syntax, returning 0 results on a proper non-transport-related error instead) seems to be a much better fit for "it just works".
> Switch to simple_query_string for better exception handling in Elasticsearch

- src/Builder.php
In relation to this https://github.com/laravel/scout/pull/37:
Since the `getTotalCount` method was added to engines to solve pagination issues. https://github.com/laravel/scout/pull/52
Can we also change the builder paginate method to support `LengthAwarePaginator`?
> Return length aware paginator

- src/Engines/ElasticsearchEngine.php
- tests/ElasticsearchEngineTest.php
In elasticsearch, _simple_query_string_ (as well as _query_string_) are special types of queries that pass directly through to the underlying Apache Lucene instance. Generally speaking, you don't want to give users direct access to the Lucene instance because the query accepts special fulltext operators  (+,|,~,*,-,etc...). Using these operators, a person could craft very powerful fulltext queries. Possibly inadvertently! The worry is, the user could accidentally bring the elasticsearch cluster down by doing TOO large of a search.
Furthermore, using _simple_query_string_, you forgo portions of the analyzation and tokenization processes that elastic is known for.
It makes a lot more sense to craft a match query, that accepts and analyzes/tokenizes the given keywords in a way that is more …
> Changed main Elasticsearch query to use a "match"

- src/Builder.php
- tests/BuilderTest.php
Gets the "per page" value from the `Illuminate\Database\Eloquent\Model` instead, similar to how `Illuminate/Database/Eloquent/Builder` currently works.
Since `$perPage = 15` on the model base-class, the default param value is not needed anymore.
> Get perPage from Illuminate model

- src/Console/ClearCommand.php
- src/ScoutServiceProvider.php
This PR adds the ability to clear all indexed documents for the given model. This is very useful in conjunction with situations when you want to refresh your migrations with --seed option during development.
> add the ability to delete all indexed documents for the given model

- src/Jobs/MakeSearchable.php
There are 2 cases that might appear and cause exceptions:
* A single model is saved outside global scope (e. g. `Post::create(['deleted_at' => Carbon::now]);`)
* A single model became not valid after dispatching and before queue execution.
> Check models collection on emptiness in queue

- src/Searchable.php
- tests/SearchableTest.php
Solves #104.
This is important when using PostgreSQL and SQL Server (for tables without a clustered key)
because the order of the result set is undefined.
Without this PR on postgresql you can something like this
```php
➔ artisan scout:import "App\Post"
Imported [App\Post] models up to ID: 310
Imported [App\Post] models up to ID: 1002
Imported [App\Post] models up to ID: 236
Imported [App\Post] models up to ID: 513
Imported [App\Post] models up to ID: 1137
Imported [App\Post] models up to ID: 97
Imported [App\Post] models up to ID: 313
Imported [App\Post] models up to ID: 627
Imported [App\Post] models up to ID: 927
Imported [App\Post] models up to ID: 1213
Imported [App\Post] models up to ID: 1496
Imported [App\Post] models up to ID: 1711
Imported [App\Post] models up to ID: 150
Imported …
```
> Explicitly set the order when importing or flushing all models to or from the index.

- src/Engines/ElasticsearchEngine.php
if a model has a globalScope, when using search will cause a warning
> fix undefined offset when using global scope

- src/Builder.php
- src/Engines/AlgoliaEngine.php
- src/Engines/ElasticsearchEngine.php
- src/Searchable.php
I'm a huge fan of Scout! It's really simple to use, love that it supports a paid and open-source driver, and that it's built with the intention of being a simple search implementation.
With that being said, I think that it would be feasible to add a callback to the `performSearch()` method of each engine that allows the developer more flexibility in terms of building a search query that is relevant to their application. While both Agolia and Elasticsearch have a vast amount of parameters, I don' think this package needs to re-invent those through additional methods or through arbitrary option arrays. This can be accomplished with a simple callback that provides a filter where you can bring your own query into the mix.  
    
**Example Implementation**
``` php …
```
> Added a callback to the perform search method.

- src/Builder.php
Adds an orders property to Builder. Generally you'll want to order by relevancy but not always. This allows drivers to be more flexible with ordered queries.
> Add orderBy support to Builder

- src/Engines/AlgoliaEngine.php
Right now the `objectID` is always sent to the Algolia index and it's used to fetch the results from the DB with `whereIn`.
So I think we could use that same key to map the results, that way the programmer won't be forced to return the primary key in the `toSearchableArray` method.
If this is not OK then we could modify the line 47 to always merge the primary key
`return array_merge(['objectID' => $model->getKey()], $array);`
But i think it's not necessary since both the primary key and the object ID should contain the same value, right?
> Map with objectID instead of primary key

- src/Engines/AlgoliaEngine.php
A small spelling fix in AlgoliaEngine@performSearch to rename the variable $agolia to $algolia.
> fix agolia variable misspelling

- src/Searchable.php
There may be occasions when you would like to sync your Searchable models outside of your default queue. Currently, this can be done by defining a new connection in the queue config and then overriding syncWithSearchUsing() on any model that uses the Searchable trait. 
While this works, it's a little overkill unless you are using a different queue driver. In these instances, it would be nice to simply use a different queue name, rather than a separate connection.
Based on feedback from an earlier PR, this PR creates a new method on the Searchable trait that can be overridden on a per model basis. It does not require any new config options and works in a manner that is similar to the syncWithSearchUsing() method.
> Allow syncing on default queue connection with custom queue name

- src/Builder.php
- src/Engines/AlgoliaEngine.php
- src/Engines/ElasticsearchEngine.php
- src/Engines/Engine.php
This is the getKeys feature I suggested here: https://github.com/laravel/scout/issues/138
It would be nice to have the option to return only ids of search results as opposed to the entire Eloquent collection.
> Bypass mapping of Eloquent objects and return just the keys of results

- composer.json
Since elasticsearch is no longer supported as part of the main package removing elasticsearch from keywords and elasticsearch/elasticsearch from the suggests.
> Remove references to elasticsearch in composer.json

- src/SearchableScope.php
Currently the chunk size is fixed at 100 which, at least for Elasticsearch, renders the import process quite slow.
For 100 000 records import time can be lowered 3 times by increasing the chunk size to about a thousand:
This change allows for setting a custom chunk size in `config/scout.php` as `searchableChunkSize` option.
It is fully backwards compatible and doesn't affect existing applications in any way as  far as I know.
> Allow for customizing searchable chunk size

- src/Searchable.php
I think that this method would be more useful if it returns the result from the callback
> Return the result from callback in withoutSyncingToSearch

- src/Builder.php
- tests/BuilderTest.php
In reference to https://github.com/laravel/scout/pull/191 this pull request adds the macroable to the builder.
> Add macroable to scout builder

- src/Builder.php
Adds a method to get the raw search results, unmapped, from the builder.
Relates to #190 & #114 
If accepted, I will also make a pull request for the 3.0 branch.
> Add getSearchResults on the builder

- src/Engines/AlgoliaEngine.php
refer to my pull request in https://github.com/ErickTamayo/laravel-scout-elastic/pull/66
```php
collect([0 => ['id' => 1], 1 => ['id' => 2], 2 => null, 3 => ['id' => 3]])->filter()
```
would get 
```php
collect([0 => ['id' => 1], 1 => ['id' => 2], 3 => ['id' => 3]])
```
which would make `paginate()` returned an object rather than list.
> Chain `values` method in map function

- src/EngineManager.php
If your `SCOUT_DRIVER` environmental variable is set to `"null"`, the `env()` helper will convert that to the value `NULL`. The current workaround is to set the value to `'"null"'`, which forces `env()` to load it as a string, or to add a check to your `scout.php` config file.
This updates `getDefaultDriver()` to return the string `"null"` if the value of `config('scout.driver')` returns `NULL`.
> Use string "null" if default driver is set to NULL

- src/EngineManager.php
Fix for NullDriver introduced in https://github.com/laravel/scout/pull/224 is PHP7 only.
Thanks to @royscheepens for [noticing](https://github.com/laravel/scout/commit/84762c8ed51cb57f09b5f465e09993e48baf9d55#commitcomment-24295476).
> Fix PHP 5.6 compatibility for null driver

- src/Console/FlushCommand.php
- src/Events/ModelsFlushed.php
- src/SearchableScope.php
When bulk importing models for index via the console we can already see the progress of the import with what ID has been reached on the models at the end of each chunk.
I flushed a huge amount of models from elastic earlier, as there was no visual clue of progress it just felt like the command had halted for some reason, one might think there is a connection issue to the their search server for instance.
This PR adds the same functionality to the flush command, it will now look this:
> Show flush progress in the console.

- .travis.yml
- composer.json
- phpunit.xml.dist
- tests/AbstractTestCase.php
Updated `phpunit/phpunit` to `~6.0` and `mockery/mockery` to `~1.0`.
Dropped support to `PHP 5.6`, as PHPUnit 6.0 [requires PHP 7.0](https://github.com/sebastianbergmann/phpunit/blob/master/composer.json#L25).
PS: I've used [this commit](https://github.com/laravel/framework/pull/17864) from `laravel/framework` to prevent failed tests.
> [4.0] Updated to PHPUnit 6 and Mockery 1

- src/Builder.php
- src/Engines/AlgoliaEngine.php
- src/ModelObserver.php
- src/Searchable.php
- tests/AlgoliaEngineTest.php
- tests/Fixtures/TestModel.php
This PR attempts to introduce the ability to keep soft deleted records in the index in query it if needed.
If you set the `scount.soft_delete` configuration attribute to true, scout will start appending a `__soft_deleted` attribute with your records, its value will be 0 or 1 depends on the state of the Model.
By default a `where` rule is added that prevents bringing soft deleted records, but you can use `User::search('maroon5')->withTrashed()->get()` to bring soft deleted models as well.
This change will require custom Engines to be modified to properly handle the new feature, the changes needed are:
- Merging the scout metadata array while updating/adding records `array_merge($model->toSearchableArray(), $model->scoutMetadata())`
- Use `Model::withTrashed()` while mapping the records …
> Ability to keep soft deleted records

- src/ModelObserver.php
- src/Searchable.php
- tests/ModelObserverTest.php
Hey.
I've come across this issue where I wanted to conditionally make some models searchable. The example I had is with `Post`s. The posts in my system can be in "draft" or published state. If a post is in the "draft" state, I would not like to make it searchable.
The current state of Scout does not let us disable model syncing per instance but per class only.
To "disable" syncing for posts in the "draft" state, I've ensured that the `searchableArray()` method returns an empty array. While it does indeed ensure that the "draft" posts won't be synced, it sends a request to make the model searchable with empty data which is useless and wasting indexing operation if you're using a driver such as Algolia.
This PR adds a simple "hook" that each model can implement to determine if it should be …
> Conditionally make a model instance searchable

- src/SearchableScope.php
Hey.
This PR is ensuring that when we perform a bulk import using the EloquentBuilder it will only import the models that `shouldBeSearchable()`. We use the EloquentBuilder when we do an import from the command line:
```bash
php artisan scout:import "App\Model"
```
This PR fixes #244
> Import only searchable models when performing a bulk import using EloquentBuilder

- src/ModelObserver.php
- tests/ModelObserverTest.php
Related to #251.
Listening to `created` and `updated` events instead of `saved` presents a problem when index includes attributes that come from relationships (ie: product index includes dealer name from another model, post has images that are stored separately etc.), because those events aren't triggered when touching parent timestamps.
> Listen to saved event instead of created/updated

- config/scout.php
- src/ModelObserver.php
- tests/ModelObserverTest.php
As mentioned in #263 the models where `shouldBeSearchable()` returns `false` are not deleted from the search engine.
This PR makes sure those models are made unsearchable to prevent your search engine exposing data that shouldn't be available.
This PR fixes #249
> Sync conditional models

- src/Console/FlushCommand.php
- src/Console/ImportCommand.php
- src/Engines/AlgoliaEngine.php
- src/Searchable.php
- tests/AlgoliaEngineTest.php
- tests/Fixtures/AlgoliaEngineTestCustomKeyModel.php
- tests/Fixtures/TestModel.php
I had a problem similar to #44 and #267. My data is indexed with a custom ObjectID which is equal to the Eloquent ID.
I just added a new method "getScoutKey" to the SearchableTrait which returns the Eloquent key by default but can be overwritten.
This should fix both issues mentioned above.
> Use custom Key to index a model

- src/Engines/AlgoliaEngine.php
- src/Searchable.php
- tests/AlgoliaEngineTest.php
This PR fixes issue #274.
The issue is that the function `getScoutKey()` can be used to make a custom index for the model. However, the Algolia engine had no idea how to turn this custom index back into the Eloquent models. This PR provides two ways to do this, a simple, and a complex one.
The simple method is `getScoutKeyName()` which you can use to provide the Algolia engine with the name of the key to use to hydrate the Eloquent models.
```php
public function getScoutKey()
{
return $this->email;
}
public function getScoutKeyName()
{
return 'email';
}
```
However, the `getScoutKey()` method does not require that a single model attribute be returned. It could be a compound key.
```php
public function getScoutKey()
{
return $this->email . '-' . $this->name;
}
```
In this case, we cannot …
> Add getScoutKeyName() and mapScoutSearchResults() functions.

- src/Engines/NullEngine.php
Fixing the map function from amends a few days ago, appears to be missing the Builder parameter added to Engine.php
> Update NullEngine.php: add missing Builder parameter

- src/Searchable.php
This Pull Request addresses the **developer experience** while interacting with the method `Searchable::search` - adding a default value to the `$query` param.
This can be useful if the developer just want an instance of the `Builder::class`:
Before:
```php
$results = Thread::search('')->where(...)->get();
```
After:
```php
$results = Thread::search()->where(...)->get();
```
> Adds default $query value on Searchable::search

- CHANGELOG.md
- src/Console/FlushCommand.php
- src/Engines/AlgoliaEngine.php
- src/Engines/Engine.php
- src/Engines/NullEngine.php
- src/Searchable.php
- tests/AlgoliaEngineTest.php
Instead of iterating over ids from the database we use the engine itself to flush the records of an index/model.
This solves the problem where models would get out of sync with the search records and old records weren't flushed. With this implementation all records are always removed.
If there are engines which don't provide this functionality they can still iterate over the model ids if they want to.
Fixes https://github.com/laravel/scout/issues/101
@julienbourdeau would you mind also taking a look at this if this is correctly implemented? I didn't have the chance to test this with a live implementation of Algolia.
> [6.0] Use engine to flush records of model

- src/Engines/AlgoliaEngine.php
- tests/AlgoliaEngineTest.php
- tests/Fixtures/EmptyTestModel.php
If a models toSearchableArray() returns an empty array the current behaviour in the AlgoliaEngine basically ends up calling the equivalent to `collect([null])->filter()->values()->all()`which returns [] therefore we call `$index->addObjects([])` and a wasteful API request is made to Algolia, since the code filters out empty data I think the intended behaviour was not to call an indexing operation.
> [6.0] Skip empty updates

- CHANGELOG.md
- src/Searchable.php
This Pull Request adds the possibility of changing the concrete implementation of the `Builder::class`. Behind the scenes, the developer can now specify is own implementation doing:
```php
$this->app->bind(
\Laravel\Scout\Builder::class,
\My\Custom\Builder::class
);
```
> [6.0] Allow to change the builder implementation using the container

- .travis.yml
This Pull Request removes the need of `elasticsearch` service from `.travis.yml`. Unless I am missing something we don't need it right?
> [6.0] Removes elasticsearch service from .travis.yml

- tests/SearchableTest.php
This was added in #105 but wasn't used then and is still not being used.
> [7.0] Remove test stub ModelStubForRemoveAllFromSearch

- src/SearchableScope.php
- tests/SearchableScopeTest.php
Using chunkById is dramatically faster when importing millions of rows.  This issue was originally reported in #182.
On a table with 1,632,576 rows, using the null scout driver so we don't have any noise from HTTP requests, an import goes from 29 minutes and 57 seconds to 28 seconds.
Before:
```
$ time php artisan scout:import "App\User"
All [App\User] records have been imported.
php artisan scout:import "App\User"  14.80s user 3.69s system 1% cpu 29:57.14 total
```
After:
```
$ time php artisan scout:import "App\User"
php artisan scout:import "App\User"  17.18s user 4.06s system 73% cpu 28.809 total
```
Concerns:
`chunkById` currently removes all ORDER BY clauses.  If someone had called `searchable` like this it wouldn't work as expected anymore:
```php
App\Order::where('price', '>', …
```
> [8.0] Use chunkById instead of chunk

- src/EngineManager.php
- src/Engines/AlgoliaEngine.php
- tests/AlgoliaEngineTest.php
When skipping records during updates on Algolia items, we should ignore any metadata as this shouldn't be a factor on wether to index or not. Only records which have at least one key value pair for indexing should be indexed.
This fixes a bug where empty records with soft deleted enabled were still being updated. Fixes https://github.com/laravel/scout/issues/350
> [7.0] Fix empty update with soft delete

- src/Engines/AlgoliaEngine.php
- tests/AlgoliaEngineTest.php
This prevents un-expected sorting when working with the json data. The tests still passed because plucking the id from the sorted collection will give you the expected sort order. Working with the data in JS, for example, will not. Not confident enough with testing to devise a test for this I'm sorry :-(
> [7.0] Calling values() on sorted collection to reset the array keys.

- src/EngineManager.php
I think this is a copy/paste from https://github.com/laravel/framework/blob/e6c8aa0e39d8f91068ad1c299546536e9f25ef63/src/Illuminate/Session/SessionManager.php#L204 and is not meant to say `session` but rather `Scout`.
> Fixing PHPdoc referencing session driver

- src/Engines/AlgoliaEngine.php
This allows calling methods like `multipleQueries()` on the Algolia search client easily.
I'm not sure if tests are needed for this. Please advise.
This PR allows calls like this:
```php
User::searchableUsing()->multipleQueries();
// or
app(EngineManager::class)->engine()->multipleQueries($indices);
```
> Add __call() method to AlgoliaEngine

- .travis.yml
Update **.travis.yml** file to run tests against Laravel **5.6** version.
> [7.0] Tests against Laravel 5.6

- .gitignore
- phpunit.xml.dist
This **PR** will:
- Remove legacy phpunit flag,  **syntaxCheck="false"**:
- That configuration setting has not had an effect in years. It was removed long ago.
- Ignore **.phpunit.result.cache**
**See:**
> [7.0] Removed legacy phpunit flag

- .styleci.yml
Alpha ordered imports are now the default for the laravel preset on styleci.io.
> [7.0] Update .styleci.yml

- src/Console/ImportCommand.php
- src/Searchable.php
Allow setting an optional chunk size when running a batch import.
This is particularly helpful if you'd like to index a model using a different batch size than the default set for the app.  Ideally it may be nice to customize batch sizes per model, instead of a single shared config value to be used across the entire app.
This is a functional workaround as it exposes in the CLI an already available chunk size parameter in the `Collection::serializable` extension method.
This is very useful for reducing the overhead of queries/update index calls for simpler indexable models. (For example, being able to batch 10k at a time instead of the default 500).  Same applies for potentially complex indexable items where you'd want to reduce memory overhead by indexing less than the default at a time.
> [8.x] Optional param for chunk size on scout:import

- composer.json
- config/scout.php
- src/EngineManager.php
This PR will auto set the user to be identified through Algolia through a config option. Other engines can make use of this new option as well if they want. Turned off by default to avoid breaking changes but I'd recommend to turn this on by default in the next major version.
However: I'm currently not seeing user stats appearing in the dashboard when I test:
Headers are being set properly and all so I don't know what I'm missing here. Need to ping @nunomaduro about it. In draft until this is resolved.
Closes https://github.com/laravel/scout/issues/385
> [8.x] Auto identify user

- src/Builder.php
This PR attempts to address to fix #371. The LengthAwarePaginator was being instantiated directly in the pagination methods. This solution intends to use the container to resolve that class instead. This will give other container-based configurations a chance to hook into the paginators emitted by Scout in the same way that they can hook into Paginators emitted by Eloquent.
The specific use case that leads me down this path was an observation that the following Laravel-specific code was not affecting LengthAwarePaginators from Scout.
```php
$app->resolving(LengthAwarePaginator::class, static function (LengthAwarePaginator $paginator) {
return $paginator->appends(request()->query());
});
$app->resolving(Paginator::class, static function (Paginator $paginator) {
return …
```
> Update builder class pagination methods to resolve LengthAwarePaginator using container

- tests/AlgoliaEngineTest.php
- tests/BuilderTest.php
- Using the `assertSame` to replace `assertEquals` and it can make assertion equals checking strict.
- Using the `assertCount` to assert expected is same as result count.
> Improve assertions

- src/ModelObserver.php
This PR sets `public $afterCommit = true` on Scout's `ModelObserver` class, so that the `saved`, `deleted`, `forceDeleted`, and `restored` model event callbacks, if they are triggered inside a database transaction, are not executed until that transaction has committed.
**Background**
This fixes an existing issue where incorrect data is synced to a search index if a model event Scout listens for, such as `saved`, is fired inside a database transaction.
If Scout is not set up to queue search index updates, this issue affects all code that fires the above model events inside database transactions, because Scout's observer method is executed immediately—before the transaction has committed or been rolled back—syncing stale or invalid data.
If Scout _is_ set up to use the queue this issue will …
> [8.x] Run observer callbacks after database transactions have committed

- config/scout.php
- src/ModelObserver.php
This PR re-implements #436 but makes it configurable. I added `$afterCommit` to Scout's `ModelObserver` again, but this time instead of setting it to `true` I set it based on a new config file entry called `after_commit`.
Since this PR defaults these values to `false`, this approach is completely backwards-compatible with all existing Scout installs, in application _and_ test code. I'm targeting the `8.x` branch so that apps that need it can start using this functionality immediately, and I'll submit another PR to `master` to turn it on by default in the next major version of Scout.
Closes #437.
**Alternatives**
I'm sure there are other ways to tackle this, and I'm happy to explore them, but this seemed like the simplest by far. Two other ideas I played with briefly:
- Adding an …
> [8.x] Allow running observer callbacks after database transactions have committed

- src/Builder.php
- src/Engines/AlgoliaEngine.php
- src/Engines/Engine.php
- src/Engines/NullEngine.php
- src/Searchable.php
- tests/AlgoliaEngineTest.php
At the moment Laravel Scout doesn't utilised `cursor` or `LazyCollection` which could be useful when searching large set of data. This PR bring the ability to use `get()` or `cursor()` from Eloquent query builder whenever possible.
* Add `Laravel\Scout\Searchable::queryScoutModelsByIds()` to return `Illuminate\Database\Query\Builder`.
* Add `Laravel\Scout\Builder::cursor()` to return results as `LazyCollection`
* Add `Laravel\Scout\Engines\Engine::lazyMap()` to map to `LazyCollection`
Signed-off-by: Mior Muhammad Zaki <crynobone@gmail.com>
> [9.x] Add support for cursor and LazyCollection on scout.

- src/ModelObserver.php
- tests/AlgoliaEngineTest.php
- tests/ModelObserverTest.php
This PR replaces the use of the `config()` helper to retrieve the `after_commit` value when creating the `ModelObserver`.
The reason why we would want to have this change is, we would be able to mock the configuration object when `not` extending the application within unit tests.
As these changes stand by now, they break all tests that call/create `models` using the `searchable` trait when extending the PHPUnit tests case class `[PHPUnit\Framework\TestCase]`.
Even though it is known we could use these helpers and we should be extending the framework test case class to work on apps tests, they are not resolved if the Laravel app is not present (in the unit context).
Reference: https://github.com/laravel/scout/pull/440
Thank you.
> [8.x] Use the Config facade instead

- src/ScoutServiceProvider.php
The meilisearch config is pulled like so:
https://github.com/laravel/scout/blob/13968539d7757ca662942a50983165d18d195dc3/src/ScoutServiceProvider.php#L22-L26
However, when trying to use this, it errors:
```php
php artisan scout:import App\\Models\\Model
[2021-04-06 02:48:37] local.ERROR: Trying to access array offset on value of type null {"exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type null at /application/vendor/laravel/scout/src/ScoutServiceProvider.php:25)
```
This is due to `$app['config']['meilisearch']` not existing; rather, it is available via `$app['config']['scout']['meilisearch']`. and changing line 23 fixes this error.
> [9.x] Correct meilisearch config reference

- src/Console/IndexCommand.php
- src/EngineManager.php
- src/Engines/AlgoliaEngine.php
- src/Engines/Engine.php
- src/Engines/MeiliSearchEngine.php
- src/ScoutServiceProvider.php
Ports over the `IndexCommand` from Meilisearch which is pretty handy for managing your indexes. I've also implemented a generic way so it works for all engines.
> [9.x] Meilisearch index command

- src/Console/CreateIndexCommand.php
- src/ScoutServiceProvider.php
Doesn't really matter but the class only creates an index now since the [delete part](https://github.com/laravel/scout/commit/c30f194c9005da3cff4868e3a228fbf71cda2a3a) was moved to a new command so I thought I'd give it a more descriptive name.
> Rename Index command

- .github/workflows/tests.yml
- composer.json
This removes support for PHP 7.2 and Laravel 6+7.
Basically the same changes done for [laravel/cashier-stripe](https://github.com/laravel/cashier-stripe/pull/1064)
> [9.x] Drop old Laravel versions

- README.md
This PR adds MeiliSearch as a supported search engine per #454 and #455 in the README. I used the slogan but I feel there is a kinda of word-battle between `blazing fast` and `lighting fast`. Should we remove both and just say: `hosted` and `open source` ? 
The benefit of this addition would be to know via the README that laravel scout supports MeiliSearch.
I changed the branch to master because of this line: 
> Minor features that are fully backward compatible with the current release may be sent to the latest stable branch.
If I'm mistaken tell me I'll change the branch!
> [9.x] Add MeiliSearch in Readme

- src/Engines/AlgoliaEngine.php
- src/Engines/Engine.php
- src/Engines/MeiliSearchEngine.php
- tests/Unit/AlgoliaEngineTest.php
- tests/Unit/MeiliSearchEngineTest.php
When I first created PR #439 it was under the impression we can use `QueryBuilder::cursor()` and everything works the same. However new feedback from @JosephSilber there are some limitations to doing this, including eager loading. 
* `Engine::map()` will use `Searchable::getScoutModelsByIds()` which will return eloquent collection.
* `Engine::lazyMap()` will use `Searchable::queryScoutModelsByIds()` which will return eloquent builder (where we can use `cursor()`).
I not sure if we are able to use `lazy()` or `lazyById()` as far as I know since chunking the result as we need to sort by relevant search results.
Signed-off-by: Mior Muhammad Zaki <crynobone@gmail.com>
> [9.x] Explicitly use `map()` or `lazyMap()`.

- src/Jobs/RemoveFromSearch.php
- src/Jobs/RemoveableScoutCollection.php
- tests/Fixtures/SearchableModelWithCustomKey.php
- tests/Unit/RemoveFromSearchTest.php
This PR patches the issue described in PR https://github.com/laravel/scout/pull/479.
This PR fixes the issue described above. However, if developers are customizing their Scout key via `getScoutKey()` and are utilizing queuing, they must also modify the `getScoutKeyName()` to return the name of this custom key, so that the models can be hydrated and be properly removed from indexes. I can also submit a PR to the docs repo if this gets merged in so it can instruct developers to perform this step when queuing using custom scout keys.
The `RemoveableScoutCollection` class extends the Eloquent collection class, and pulls the queueable ID's from the model's `getScoutKey()` method. This is the cleanest solution I was able to come up with the least possible intrusion and work on the developers …
> [9.x] Fix removing queued models with custom Scout keys

- src/Builder.php
fixes #481
Signed-off-by: Mior Muhammad Zaki <crynobone@gmail.com>
> [9.x] Re-query scout engine when paginate results contains insufficient keys to generate proper pagination count query

- src/EngineManager.php
- src/Engines/CollectionEngine.php
- tests/Feature/CollectionEngineTest.php
Over the weekend, I was hacking on something where I wanted to quickly use Scout without setting up any other external dependencies like Algolia or MeiliSearch.
I cooked up this quick driver that is intended for usage in **local development and small staging environments only**. It is not performant on large datasets and does not have robust fuzzy matching or anything. However, it is perfectly adequate in local development environments where you often don't have more than a couple hundred models.
However, this driver uses Eloquent's cursor method to retrieve filtered results and then uses `Str::contains` against the `LazyCollection` to match against all of the searchable columns. Note it is not possible to do those checks in the database because we do not know the data types of the …
> Collection Engine

- src/Engines/CollectionEngine.php
- tests/Feature/CollectionEngineTest.php
A minor change to the collection engine that allows case-insensitive search by simply downcasing the attribute and query arguments before calling `contains`. Using the test data at the moment a search for a lowercase `otwell` wouldn't match either of you because your names are capitalised.
> Downcase attribute and query for case-insensitive search

- src/ModelObserver.php
- src/Searchable.php
- tests/Feature/SearchableTest.php
- tests/Fixtures/SearchableModelWithSoftDeletes.php
- tests/Unit/ModelObserverTest.php
The current `ModelObserver` implementation calls `unsearchable` every time a model gets deleted. Practically, it means that the underlying engine (in our case, at StuDocu, Algolia) would be asked to delete the model from its index regardless of it actually being in the index or not.
Two methods named `wasSearchableBeforeUpdate` and `wasSearchableBeforeDelete` are implemented to respectively check if a model was searchable before being updated or deleted. `ModelObserver` gets smarter and first checks if a model was actually searchable before calling `unsearchable`, thanks to one or the other method.
Now, the flow is as follow:
* When a model gets updated and is not searchable, we first check if it was searchable using `wasSearchableBeforeUpdate`. If it was, it is made unsearchable. If it …
> [9.x] Improve observer strategy

- src/SearchableScope.php
Looks like `HasManyThrough::macro('unsearchable')` accidentaly defined same as `HasManyThrough::macro('searchable')` and makes models searchable... 
PS: I'm not tested this, because it is not used in our application.
> HasManyThrough::macro('unsearchable') fix

- src/Engines/CollectionEngine.php
This fixes an issue with the collection driver, if you have a column which is not a string, like a JSON column, The collection driver errors when trying to make the attribute lower case.
I have added a continue if the attribute is not a string.
> Fixed non string columns breaking model filter with collection driver

- src/Engines/MeiliSearchEngine.php
Meilisearch 0.21.0 [contains a breaking change](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.21.0) regarding the `filters` attribute. It was renamed to `filter` instead.
This PR addresses that by checking what version of the SDK was installed, and handling the attribute accordingly.
Not that user would need to manually add the attributes they want to filter on to the `filterableAttributes` setting, they can not be used on any field any more as one could before version 0.21.
> [9.x] Support rename of filters to filter in meilisearch 0.21.x

- src/Engines/CollectionEngine.php
- src/Engines/MeiliSearchEngine.php
- src/Jobs/RemoveFromSearch.php
- src/Searchable.php
- tests/Feature/SearchableTest.php
- tests/Fixtures/SearchableModelWithCustomKey.php
- tests/Unit/MeiliSearchEngineTest.php
- tests/Unit/RemoveFromSearchTest.php
This PR changes the use of getScoutKeyName. The most significant change is the removal of the use of the qualified column name in the `getScoutKeyName` method. Other changes are using the `getScoutKeyName` instead of `getKeyName` so people can modify what column is used to index search records. This was already possible with Algolia but not with Meilisearch.
The reason why the qualified column was removed was that if someone were to override `getScoutKeyName` (with the other changes in mind from this PR) the `toSearchableArray` wouldn't be compatible anymore as it won't append the correct column name and thus search records in Meilisearch won't index properly anymore. If we want to make `getScoutKeyName` adjustable for Meilisearch as well (as currently stated in the docs) then this change …
> [10.x] Refactor the use of getScoutKeyName

- src/Engines/CollectionEngine.php
- tests/Feature/CollectionEngineTest.php
This PR adds the ability to pass an empty search argument, which skips the search filtering step.
> [9.x] Add the ability to omit the search argument in the CollectionEngine

- src/Engines/CollectionEngine.php
- tests/Feature/CollectionEngineTest.php
- tests/Fixtures/SearchableUserModelWithCustomSearchableData.php
Fixes #518
This PR adds functionality to search inside custom searchable data when using 'collection' engine.
Let's assume there is an e-commerce application which has products and their attributes in separate tables.
- Products has many Attributes
- Attributes has many Products
Because of all the key attributes such as price is in the attribute_product pivot table we have to assign those attributes manually in the 'toSearchableArray' method in the Product modal to make the search form price working.
In such situations the collection engine does not currently support searching on custom searchable data such as price in this example.
In this MR the searching will be same as other engines such as Meilisearch engine and Algolia engine
> Fixed #518 - Searching on custom searchable data when using collection driver

- src/Engines/CollectionEngine.php
The Algolia and MeiliSearch engines both allow searchable data to be non-scalar values (e.g., an [array of ingredients](https://www.algolia.com/doc/guides/sending-and-managing-data/prepare-your-data/how-to/setting-searchable-attributes/) or [genres](https://docs.meilisearch.com/reference/features/filtering_and_faceted_search.html#example-2)).
The Collection engine, however, expects all values to be scalar, and during search, throws a `TypeError` if a model’s `toSearchableArray()` returns any non-scalar key.
```
TypeError: mb_strtolower(): Argument #1 ($string) must be of type string, array given in /path/to/project/vendor/laravel/framework/src/Illuminate/Support/Str.php:361
Stack trace:
#0 /path/to/project/vendor/laravel/framework/src/Illuminate/Support/Str.php(361): mb_strtolower(Array, …
```
> [9.x] - Collection Engine: add support for non-scalar values

- src/Builder.php
The method complements the existing `simplePaginate()` method with the option to receive the "raw" data of the search engine.
There already exists a `paginate()` and `paginateRaw()` method.
> [9.x] Add simplePaginateRaw query

- src/Builder.php
This is a followup to https://github.com/laravel/scout/pull/538#pullrequestreview-773687695 removing a fix on the 9.x branch
> [10.x] Remove obsolete code for scout key name

- src/Engines/MeiliSearchEngine.php
- tests/Unit/MeiliSearchEngineTest.php
Since `getScoutKeyName()` and `getScoutKey()` return the expected data (https://github.com/laravel/scout/pull/509) we can now build the searchable data ourselves.
This adds consistancy to the already implemented collection engine and Algolia engine that make use of a "predefined" primary key.
Furthermore, this reduces bugs on the implementation side for users that override the `toSearchableArray()` method and forget to add the primary key.
> [10.x] Provide searchable data array with primary key and value for MeiliSearch

- src/Engines/MeiliSearchEngine.php
- tests/Unit/MeiliSearchEngineTest.php
This is a backport to the changes in #546 for the 9.x branch
> [9.x] Fix issues for users providing searchable array without primary key

- src/Searchable.php
This PR is an updated version of #566, this will now check if the key is ```int``` or ```integer```
> [9.x] Optimize whereIn to use whereIntegerInRaw when primaryKey is integer

- src/Attributes/FullText.php
- src/Attributes/SearchUsingFullText.php
- src/Attributes/SearchUsingPrefix.php
- src/Builder.php
- src/Contracts/PaginatesEloquentModels.php
- src/EngineManager.php
- src/Engines/DatabaseEngine.php
- tests/Feature/DatabaseEngineTest.php
- tests/Fixtures/SearchableUserDatabaseModel.php
> This PR depends on https://github.com/laravel/framework/pull/40129
This PR adds a new database engine to Scout that's powered by the upcoming `whereFulltext` addition to Laravel's query builder. Using this, we'll be able to offer natural language search in Scout on `fulltext` indexes for Scout.
I managed to quickly set this up thanks to the existing Collection engine. We'll probably need to abstract those so functionality is shared.
The way this works is that you define the columns of your index through the `toSearchableArray` method:
```php
/**
* Get the indexable data array for the model.
*
* @return array
*/
public function toSearchableArray()
{
return [
'name' => $this->name,
'bio' => $this->bio,
];
}
```
Then use it as usual:
```php
$users = User::search('Hello world!')->get();
``` …
> [9.x] Add a DatabaseEngine

- src/Builder.php
This fixes #573 as paginateRaw is currently always treated as a void method in 9.4.0.
> Return paginator for paginateRaw (fixes #573)

- src/Engines/MeiliSearchEngine.php
Sorting in the meilisearch is for a long time and works very good so there is no reason to not implement this functionality.
https://docs.meilisearch.com/reference/features/search_parameters.html#sort
```php
$query->orderBy('date', 'desc');
$query->orderBy('price', 'asc');
```
By this query, we sort results first by date (newest) and next by price (cheapest). Sorting works like in MySQL.
> Handle sorting (Meilisearch)

- composer.json
This doesn't appear to actually be breaking anything but, nonetheless, this fixes the constraint on `illuminate/queue` to be valid.
> Fix invalid (but working) constraint

- src/Engines/DatabaseEngine.php
Doc Block for the `getPrefixColumns` method was using the same description as the `getFullTextColumns` method.
I based the description on the attribute `SearchUsingPrefix`'s `$columns` property description.
https://github.com/laravel/scout/blob/bb6bea547d7f9231dab2bb378fed12a64a000687/src/Attributes/SearchUsingPrefix.php#L12
> [9.x] Fix wrong doc blocks

- src/Engines/CollectionEngine.php
- tests/Feature/CollectionEngineTest.php
> [9.x] Fix collection engine `mapIds` bug

- src/Engines/DatabaseEngine.php
following https://github.com/laravel/scout/pull/589#issuecomment-1043061781
When trying to search a model on a column with fulltext index and naturale langage query with mysql:
```
/**
* Get the indexable data array for the model.
*
* @return array
*/
#[SearchUsingFullText(['bio'])]
public function toSearchableArray()
{
return [
'bio' => $this->bio,
];
}
```
I do:
`User::search('word1 word2')->get()`
and query executed is:
```
select *
from `users`
where (match (`users`.`bio`) against (? in natural language mode)) order by `id` desc
```
Mysql automatically order by results by relevancy based on score and we can't benefit from that. I'd like to get my users ordered something like 1, 3, 2 but always get my users ordered 3, 2, 1. So we remove default "order by" as soon as a full-text where …
> [9.x] Remove default order by model key desc in database engine when full-text index is used

- src/Engines/DatabaseEngine.php
- tests/Feature/DatabaseEngineTest.php
This PR adds support for the limit (`->take(5)`) to the DatabaseEngine (same as #569, but on the query instead of the collection).
Related issue: #594
> Add limit to database engine

- src/Engines/DatabaseEngine.php
The previous PR broke Laravel Nova implementation on Global Search where we use the following:
```php
App\Models\User::search('Laravel')->tap(fn ($query) => $query->limit(5))->get();
``` 
Callback using `tap()` take priority over default.
`limit()` take priority over `tap()` and I would consider this a breaking change.
> [9.x] Apply `limit` on `DatabaseEngine` before applying additional constraints

- src/Console/SyncIndexSettingsCommand.php
- Make the `scout:sync-index-settings` command aware of the scout prefix being used.
---
I was able to work around this by assigning the scout prefix to a variable inside the config file, like so:
```php
return [
'prefix' => $scoutPrefix = env('SCOUT_PREFIX', 'local_'),
// ...
'meilisearch' => [
'host' => env('MEILISEARCH_HOST', 'http://localhost:7700'),
'key' => env('MEILISEARCH_KEY', null),
'index-settings' => [
$scoutPrefix . 'users' => [
'filterableAttributes'=> [
'__soft_deleted',
'id',
'name',
],
'sortableAttributes' => [
'id',
],
],
],
],
];
```
But I figured the command could be made aware of the prefix instead. This change also allows defining the key as a model, so something like:
```php
return [
'meilisearch' => [
'host' => env('MEILISEARCH_HOST', 'http://localhost:7700'), …
```
> [9.x] Fix the sync index settings command not using the scout prefix

- src/Console/DeleteAllIndexesCommand.php
- src/Console/IndexCommand.php
- src/Console/SyncIndexSettingsCommand.php
- src/Engines/MeiliSearchEngine.php
- src/ScoutServiceProvider.php
This PR add some new features for Meilisearch:
- `scout:index` accept a FQCN as name argument.
- Apply filterable attribute on `__soft_deleted` when Model use SoftDeletes at index creation.
- Added a new command to delete all indexes _(only [Meilisearch](https://github.com/meilisearch/meilisearch-php/blob/440d061fafafa4f9e61104ff0a623f9d56816593/src/Delegates/HandlesIndex.php#L43) support it)_.
___
With this addition, your `Scout.php` config file will not look like this crazy repetition:
```php
'meilisearch' => [
'host' => env('MEILISEARCH_HOST', 'http://localhost:7700'),
'key' => env('MEILISEARCH_KEY', null),
'index-settings' => [
Model_A::class => [
'filterableAttributes' => ['__soft_deleted'],
],
Model_B::class => [
'filterableAttributes' => ['__soft_deleted'],
],
Model_C::class => [ …
```
> [9.x] Add command delete-all-indexes, update scout:index to allow FQCN and apply filterable on SoftDeletes

- .github/workflows/tests.yml
- composer.json
Drops support for PHP 7.3 & 7.4 and Laravel 8.x
> [10.x] Drop old PHP and Laravel versions

- UPGRADE.md
Most notable the changes from https://github.com/laravel/scout/pull/509 & https://github.com/laravel/scout/pull/657 were documented.
> [10.x] v10 Upgrade guide

- RELEASE.md
- src/EngineManager.php
- src/Scout.php
- src/ScoutServiceProvider.php
This adds user agent information to the meilisearch client to support anonymous telemetry on Meilisearch side  
https://github.com/laravel/scout/pull/678#issuecomment-1359461649
> [9.x] Add analytics for meilisearch engine

- src/Builder.php
- src/Engines/AlgoliaEngine.php
- src/Engines/DatabaseEngine.php
- src/Engines/MeiliSearchEngine.php
Closes https://github.com/laravel/scout/issues/682
This PR allows users to set extra options for their search request. Right now, Algolia and Meilisearch are supported.
```php
$results = User::search('hello world')->options([
'matchingStrategy' => 'all',
])->get();
```
> [9.x] Allow options for search requests

- src/EngineManager.php
- src/Engines/MeiliSearchEngine.php
- src/ScoutServiceProvider.php
This adds workarounds for the new casing of class names that we introduced on `meilisearch/meilisearch-php` which had more implications than we thought. This should also solve issues like https://github.com/laravel/scout/pull/685
Unfortunately PHP handles case sensitivity on some platforms differently
These changes are not necessary for the 10.x branch which (when released) will already handle these case changes
> [9.x] Make scout compatible with new meilisearch casing

- src/Engines/MeiliSearchEngine.php
Methods `MeiliSearchEngine::update()` and `MeiliSearchEngine::delete()` both expect a Illuminate\Database\Eloquent\Collection of models. 
For my use case I used to fine-tune this collection using `->filter()` on it. Using ->filter() on collection might result in a collection that doesn't wrap a [list](https://www.php.net/manual/en/function.array-is-list.php) anymore, but an array with non-consecutive keys. While `MeiliSearchEngine::update()` implementation handle this well, calling the `MeiliSearchEngine::delete()` method results in following error from Meilisearch:
> Meilisearch ApiException: Http Status: 400 - Message: Json deserialize error: invalid type: map, expected a sequence at line 1 column 0 - Code: bad_request - Type: invalid_request - Link: …
> [9.x] Handle non-consecutive key collection on MeiliSearch document deletion

- composer.json
- src/ScoutServiceProvider.php
- tests/Feature/MeilisearchEngineTest.php
This PR fixes a missing variable import for the Meilisearch client in its service provider.
Fixes https://github.com/laravel/scout/issues/693
> [9.x] Fix missing variable in closure

- src/Engines/CollectionEngine.php
- src/Engines/DatabaseEngine.php
- tests/Feature/CollectionEngineTest.php
- tests/Feature/DatabaseEngineTest.php
This PR enables `->orderBy()` for the `collection` & `database` engines.
Currently, when using those engines, results are by default ordered by the model key or by any full text columns. Now you may call `->orderBy('column', 'asc');` on the Scout Builder, as you would for other engines, it will be added to the query.
Before:
```php
Users::search('otwell')->orderBy('created_at', 'desc')->get(['id', 'created_at']);
//[{
//       id: 1,
//       date: 2023-01-11 00:00:00.0,
//    },
//    {
//        id: 2,
//        date: 2023-03-11 00:00:00.0,
// }],
```
Now:
```php
Users::search('otwell')->orderBy('created_at', 'desc')->get(['id', 'created_at']);
//[{
//       id: 2,
//       date: 2023-03-11 00:00:00.0,
//    },
//    {
//       id: 1,
//       date: 2023-01-11 00:00:00.0,
// }],
```
> [9.x] Enable order by for `collection` & `database` engines

- src/Searchable.php
Please check https://github.com/laravel/laravel/pull/6010 for details about this pull request.
> [9.x] Adds types to `makeAllSearchableUsing`

- .github/ISSUE_TEMPLATE/1_Bug_report.md
- README.md
- UPGRADE.md
- composer.json
- config/scout.php
- src/Console/SyncIndexSettingsCommand.php
- src/EngineManager.php
- src/Engines/MeilisearchEngine.php
- src/ScoutServiceProvider.php
- tests/Feature/BuilderTest.php
- tests/Feature/MeilisearchEngineTest.php
- tests/Unit/MeilisearchEngineTest.php
- Reference: https://github.com/meilisearch/meilisearch-php/releases/tag/v0.27.0
- Reference: https://docs.meilisearch.com/learn/advanced/pagination.html#numbered-page-selectors 
- Reference: https://github.com/meilisearch/meilisearch/releases/tag/v0.30.0
- Reference: https://github.com/meilisearch/meilisearch/releases/tag/v0.21.0
- Reference: https://github.com/meilisearch/meilisearch-php/releases
> [10.x] Meilisearch v1 support 

- src/Engines/MeilisearchEngine.php
- tests/Unit/MeilisearchEngineTest.php
`getUnqualifiedScoutKeyName` doesn't exist anymore. Since `getScoutKeyName` sends back to `\Illuminate\Database\Eloquent\Model::getKeyName` which is unqualified, the fix is straightforward.
> Fix missing function issue

- src/Builder.php
- src/Contracts/PaginatesEloquentModelsUsingDatabase.php
- src/Engines/DatabaseEngine.php
- tests/Feature/DatabaseEngineTest.php
Hey there!
This is a follow up PR to https://github.com/laravel/scout/pull/726 which uses the suggested approach to introduce this ability in a non-breaking fashion.
It does this by introducing a new contract: `PaginatesEloquentModelsUsingDatabase`, which includes support for specifying a `$pageName` for both the `paginate` and `simplePaginate` methods. Technically, this replaces `PaginatesEloquentModels`, which is no longer used in the codebase at all. However, I have left the logic in place in case a 3rd party driver uses that contract. Perhaps we could remove it in a future version of Scout?
I have left the old `simplePaginate` method on the `DatabaseEngine` so that should anybody be doing something strange like injecting it directly, the signature remains identical. The old method …
> [10.x] Adds support for custom page names using the database engine

- src/Engines/AlgoliaEngine.php
- src/Engines/MeilisearchEngine.php
- tests/Unit/AlgoliaEngineTest.php
- tests/Unit/MeilisearchEngineTest.php
The Algolia and Meilisearch engines currently do not handle empty `whereIn` clauses correctly. Algolia seems to ignore it whereas Meilisearch gives an error. This pull request aims to resolve this.
I've copied the fix that was included in algolia/scout-extended where they just send `0=1`.
https://github.com/algolia/scout-extended/pull/265/files
I've used the `IN` operator that was introduced in Meilisearch v0.29:
https://github.com/meilisearch/product/discussions/407#discussioncomment-3084053
This automatically handles the empty case and is a more elegant way of doing it instead of the `OR` operator.
> Handle empty whereIn clause

- src/Jobs/MakeSearchable.php
- src/Searchable.php
- tests/Feature/SearchableTest.php
- tests/Unit/MakeSearchableTest.php
In the projects at work, we use Laravel's lazy loading prevention. But when installing and using Scout, I noticed that Scout does not use `makeAllSearchableUsing` when making specific models searchable (which I thought at first). This causes lazy loading errors when the `toSearchableArray` method expects certain relations to be loaded (as is the case when importing all models because it then uses the `makeAllSearchableUsing` method).
```php
public function toSearchableArray() : array
{
return [
// This causes lazy loading on every model that is made searchable
'some_relation_attribute' => $this->someRelation->attribute
];
}
$someModels->searchable();
$parentModel->someRelation()->searchable();
```
So to fix this, I propose introducing a new method: `makeSearchableUsing`. This method …
> [10.x] Add 'makeSearchableUsing' method (to allow eager loading when making specific models searchable)

- src/Engines/MeilisearchEngine.php
n #683 options were added to the search request.
In https://github.com/laravel/scout/commit/ee11fd3520264cceb1e78134ae419e87b9d5e0ad the line was removed.
This PR just re-adds the line.
> re-add options for search requests

- src/Searchable.php
- tests/Unit/MakeSearchableTest.php
This pull request fixes `makeSearchableUsing` not being able to be called, and add tests on it.
> [10.x] Fixes `makeSearchableUsing` not being able to be called

- src/SearchableScope.php
- tests/Unit/SearchableScopeTest.php
Scout is currently experiencing compatibility issues with  Microsoft SQL Server databases, as an error is thrown when attempting to import models on Scout. The error message is as follows:
```
SQLSTATE[HY000]: General error: 20018 A column has been specified more than once in the order by list. Columns in the order by list must be unique. [20018] (severity 15) [select top 500 * from [users] order by [users].[id] asc, [id] asc] (Connection: sqlsrv, SQL: select top 500 * from [users] order by [users].[id] asc, [id] asc)
```
The regression was introduced in the changes made during the pull request at https://github.com/laravel/scout/pull/509. It happens because two "order by" statements are used with the same column name. While this doesn't pose any problems with other database drivers, it …
> [10.x] Fixes usage with `sqlsrv` databases

- src/Builder.php
- src/Engines/MeilisearchEngine.php
- tests/Unit/MeilisearchEngineTest.php
Closes #750
Fixes occasions with meilisearch where users can set options on the `Builder` class like `attributesToRetrieve` which would restrict the search engine to include the unique identifiers on the search result.
Unfortunately if users [customize their search engine calls](https://laravel.com/docs/10.x/scout#customizing-engine-searches) this issue would still be possible as we have no control over the search result provided by the user.
> [10.x] Override attributesToRetrieve config to ensure search result is complete

- src/Searchable.php
- tests/Feature/SearchableTest.php
Hello,
this PR improves the Scout integration when using custom keys for Searchable Models.
This problem was already addressed in the following issue:
https://github.com/laravel/scout/issues/741
In one of our applications, we use incrementing IDs as the primary key for our models. Additionally, we are using the `HasUuids` trait to add a uuid column on top of the incrementing id. We did that because we didn't want to expose our incrementing IDs to the front end (and the search engine) due to security concerns. 
We have done that by modifying the `getScouteKey' method.
```PHP
public function getScoutKey(): string
{
return $this->uuid;
}
```
So far, so good indexing of these models works. But when we want to use the `Model::search()->get()` method within the query builder, we get a database …
> Add Configurable Scout Key Type

- composer.json
- src/Engines/MeilisearchEngine.php
Meilisearch supports backed enums when inserting data, by extension I think it would make sense to also support filtering by them.
> Meilisearch: support filtering with backed enums
