laravel/scout

composer.json
Update the email to taylor@laravel.com instead of gmail.
=> Use same email as in laravel/framework

src/Builder.php
When requesting results using scout and the paginate method the request resulted in an undefined index on 'nbPages' #21
=> Pagination Issue: nbPages undefined index fix

src/EngineManager.php, src/ScoutServiceProvider.php, src/Searchable.php
=> Import classes

.travis.yml
Use `--prefer-dist` with Travis
=> Use --prefer-dist with Travis

composer.json
=> Order require and keywords

composer.json, src/Engines/AlgoliaEngine.php, tests/AbstractTestCase.php, tests/AlgoliaEngineTest.php, tests/BuilderTest.php, tests/Fixtures/AlgoliaEngineTestModel.php, tests/MakeSearchableTest.php, tests/ModelObserverTest.php
=> Switch tests to PSR-4

src/Builder.php, src/Console/ImportCommand.php, src/EngineManager.php, src/Engines/AlgoliaEngine.php, src/Engines/Engine.php, src/Engines/NullEngine.php, src/Events/ModelsImported.php, src/Searchable.php
Fix docblocks and use FQN syntax
=> Fix docblocks and use FQN syntax

src/Engines/ElasticsearchEngine.php
As the local variable is used only one time
=> Pagination simplification

src/ModelObserver.php
=> Dry ModelObserver

config/scout.php, src/Engines/ElasticsearchEngine.php, tests/ElasticsearchEngineTest.php
=> Add missing EOA commas.

composer.json
Move some dev dependencies to require.
=> Move some dev dependencies to require.

composer.json
Provide suggested packages versions
=> Provide suggested packages versions

src/EngineManager.php, src/Engines/Engine.php, src/Searchable.php
=> Fix some docblocks.

src/Engines/AlgoliaEngine.php
Declare the missing Algolia client.
=> Declare the missing Algolia client.

src/Engines/AlgoliaEngine.php, src/Engines/ElasticsearchEngine.php
Returns the expected `\Illuminate\Database\Eloquent\Collection`.
=> Return a Eloquent\Collection.

readme.md
The "based" suffix should be hyphenated.
=> Add hyphen in readme.

composer.json
Because is supported out of the box
=> Add elasticsearch keyword

src/Console/FlushCommand.php
=> fix flush command when php5.6

src/Engines/AlgoliaEngine.php
When using eager loading / joining on results for example.
=> Fixes ambiguous ID issues for Algolia search results.

src/Engines/ElasticsearchEngine.php
When using eager loading / joining on results for example.
=> Fixes ambiguous ID issues for Elastic search results.

src/Engines/ElasticsearchEngine.php
=> Elasticsearch - don't trigger bulk update for empty bodies

src/ScoutServiceProvider.php
This contribution follows on the work I began in laravel/framework, here:
https://github.com/laravel/framework/pull/18506
Thank you for your consideration.
=> Make consistent the disuse of helper functions within ServiceProviders

src/Builder.php
Get the raw results of the search.
=> Add raw method to builder

src/EngineManager.php
2 PR's have just been merge to 2.0 branch.
In case there is a new release of the 2.0 branch, we'd love to have the user agent added. 🙂
=> Add Algolia user agent

composer.json
=> [3.0] Some composer adjustments.

config/scout.php
How much wood could a wood chuck chunk?
=> Fix Chunk typo

src/EngineManager.php
Follow Algolia UA convention.
https://github.com/algolia/algoliasearch-client-php/pull/140
=> Use addSuffixUserAgentSegment() method

src/Builder.php
=> Rewrite paginateRaw method for Builder class 

config/scout.php, src/Builder.php, src/Searchable.php, tests/BuilderTest.php
Same as #256 but variable casing is fixed.
=> Uncouple builder

src/Searchable.php
Adding the Eloquent SoftDeletes class to Searchable trait for indexing soft delete objects when i run php artisan scout:import command
=> Adding the Eloquent SoftDeletes class to Searchable trait

composer.json
=> Update git dev-master branch alias

src/Builder.php
Bring missing `when`/`tap` method back.
=> add "when"/"tap" method on Builder

readme.md, src/Builder.php, src/Engines/NullEngine.php, src/Searchable.php
Some changes from 5.0 which weren't on master.
=> [6.0] Add 5.0 changes

src/Searchable.php, tests/AlgoliaEngineTest.php, tests/SearchableTest.php
Enfore Laravel style-guide, new without braces.
=> [6.0] New without braces.

src/SearchableScope.php, tests/AlgoliaEngineTest.php, tests/SearchableTest.php
Remove useless imports, and ensure they are correctly sorted.
=> [6.0] Remove useless imports, and ensure they are properly sorted.

src/Console/FlushCommand.php
No need to inject the dispatcher.
=> [6.0] No need to inject the dispatcher.

CHANGELOG.md
This Pull Request fixes the ChangeLog of the version `6.1.1`.
=> Fixes CHANGELOG for v6.1.1

src/Searchable.php
=> [6.0] Fix a docblock.

composer.json, src/EngineManager.php, src/Engines/AlgoliaEngine.php, tests/AlgoliaEngineTest.php
This PR aims to upgrade the Algolia API client to v2.
See issue #348.
=> [7.0] Upgrade Algolia API client to v2

CHANGELOG.md, UPGRADE.md, src/EngineManager.php
This Pull Request addresses the migration of Laravel Scout to Algolia PHP API Client v2:
- Adds an `UPGRADE.md ` - Since I believe that there are developers relying on the behavior of the Algolia PHP Client V1 (https://github.com/laravel/scout/commit/c1f44c7b09bc053d400b2962b3899761ff3f9e75)
- Better feedback when dependencies are not installed correctly (https://github.com/laravel/scout/commit/768ed1cc511ca8de723085bd29ff29e5c4cb4340). Here is a example on Laravel Nova:
- Re-adds user agent that got removed [here](https://github.com/laravel/scout/pull/349/files#diff-2b5d09b85f885bf28d3530a5a5a20309L31) (https://github.com/laravel/scout/commit/9e23cf3a2cf286c1f0a8b36310a69f2e52db53f1)
Here is the Pull Request that updates the documentation: https://github.com/laravel/docs/pull/4964
=> [7.0] Adds upgrade guide and better feedback

src/EngineManager.php
This Pull Request fixes a typo on Algolia dependency warning.
=> Fixes typo on Algolia dependency warning

src/ScoutServiceProvider.php
Otherwise we have to publish scout config to use package.
=> [8.x] Merge default scout configs

.github/workflows/tests.yml, composer.json
=> [8.x] Laravel 8 support

src/SearchableScope.php
Fixes https://github.com/laravel/scout/issues/414
=> [8.x] Fix HasManyThrough relationships

src/Builder.php
Fixes issue https://github.com/laravel/scout/issues/420
=> [Fix] Builder callback property type

.github/workflows/tests.yml, composer.json
Currently blocked by https://github.com/algolia/algoliasearch-client-php/pull/644
=> [8.x] PHP 8 Support

src/Builder.php, tests/BuilderTest.php
Signed-off-by: Mior Muhammad Zaki <crynobone@gmail.com>
=> Add ability to use simplePaginate with Laravel Scout.

composer.json, config/scout.php, src/EngineManager.php, src/Engines/MeiliSearchEngine.php, src/ScoutServiceProvider.php, tests/AlgoliaEngineTest.php, tests/Fixtures/EmptySearchableModel.php, tests/Fixtures/SoftDeletedEmptySearchableModel.php, tests/MeiliSearchEngineTest.php
Integration suggestion discussed in #454
=> [9.x] Support MeiliSearch Engine

src/Engines/NullEngine.php
Adds missing methods of the base class.
=> [9.x] Add missing NullEngine class options

tests/AlgoliaEngineTest.php
Fixed typo on class name
<pre><b>Aloglia</b>CustomKeySearchableModel -> <b>Algolia</b>CustomKeySearchableModel</pre>
=> Fix typo on Algolia test

src/Builder.php
=> Remove useless variable in simplePaginate

.github/ISSUE_TEMPLATE/1_Bug_report.md
To better identify what the OP is using.
=> [9.x] Ask about Scout driver in issue template

src/Engines/MeiliSearchEngine.php
=> Revert "meilisearch engine AddDocuments with getScoutKeyName"

config/scout.php, src/EngineManager.php
=> feat: add timeout options for algolia client

composer.json
Update to the latest version of meilisearch-php, compatible with the latest version of MeiliSerach (v0.21.0)
=> Update meilisearch-sdk version to v0.19.0

tests/Feature/BuilderTest.php
This PR adds tests for the `paginateRaw` method in `Builder.php`. See #574 and #573.
=> Added tests for paginateRaw

src/Engines/MeiliSearchEngine.php, tests/Unit/MeiliSearchEngineTest.php
I've recently opened an issue (#586) and found out this was a pending PR that wasn't submitted yet
Fixes #572
=> Implements Meilisearch sort on paginate

.github/ISSUE_TEMPLATE/1_Bug_report.md
This adds an additional field to the bug report template to give more hints about the user environment.
=> Update bug report issue template

composer.json
Suggest current versions of the sdks
=> Update suggested sdk versions of algolia and meilisearch

src/Engines/DatabaseEngine.php
Fix for https://github.com/laravel/scout/pull/606#issuecomment-1088336151
=> Fixed access to undefined key.

.github/ISSUE_TEMPLATE/1_Bug_report.md
Think this will uncover a lot of things before reports are even filed.
=> Ask for Meilisearch CLI version

tests/Feature/DatabaseEngineTest.php
=> Add tests for `tap` usages on `DatabaseEngine`

src/Console/DeleteIndexCommand.php
This PR allow usage of FQCN when using `delete-index` command
=> Allow FQCN to delete-index command

.gitattributes, .github/workflows/static-analysis.yml, composer.json, phpstan.neon.dist, src/SearchableScope.php
This pull request adds type checking to this repository.
=> [9.x] Adds type checking
